### ISSUE TITLE
Seems zhfonts can't support italic font with "\em"

### ISSUE THREAD

**Issue by thinkhy** [liyanrui/zhfonts#10]
There are some labels "\em" which is used for italic font in my tex generated from markdown doc using Pandoc tool. When I tried to convert tex with zhfonts module used to PDF,  all the text after "\em" are lost.

Any clue to resolve this problem? Thanks a lot.

**Comment by liyanrui** [comment]
Try this:

```
\usemodule[zhfonts]
\setupbodyfontenvironment[default][em=bold] 
\starttext
{\em 测试}
\stoptext
```
