### ISSUE TITLE
protrusions不起作用

### ISSUE THREAD

**Issue by Fusyong** [liyanrui/zhfonts#14]
用的是最新的：

ConTeXt  ver: 2022.01.21 20:13 LMTX
 fmt: 2022.1.24  int: english/english

![image](https://user-images.githubusercontent.com/15652226/153738213-95a2d12f-b8d8-4fbf-b3eb-010234f793bd.png)

**Comment by liyanrui** [comment]
用的是哪款字体？

**Comment by Fusyong** [comment]
抱歉，是我对命令不熟悉导致的。解决了。

我用的是官方定义好的字体，配置是：

```latex
\usetypescriptfile[mscore]
\usebodyfont   [mschinese,12pt]
```
