### ISSUE TITLE
feature request: define new font set based on zhfonts

### ISSUE THREAD

**Issue by walkthetalk** [liyanrui/zhfonts#15]
如何基於zhfonts定義新的字體集合？

\definexxx[newfontset][zhfonts]

使用與設置zhfonts同樣的語法設置newfontset：
\setupnewfontset[xxx][yyy]

**Comment by liyanrui** [comment]
你可以考虑直接用 ConTeXt 的 \definefallbackfamily 和 \definefontfamily 定义字体集。

例如

\usemodule[zhfonts][style=none,size=none] % 仅用 zhfonts 压缩标点

\definefallbackfamily[myfont][rm][notoserifcjksc][preset=range:chinese]
\definefallbackfamily[myfont][ss][notosanscjksc][preset=range:chinese]
\definefallbackfamily[myfont][tt][notosansmonocjksc][preset=range:chinese]

\definefontfamily[myfont][rm][latinmodernroman]
\definefontfamily[myfont][ss][latinmodernsans]
\definefontfamily[myfont][tt][latinmodernmono]
\definefontfamily[myfont][math][xitsmath]

```
\setupbodyfont[myfont,12pt]
\starttext
测试 Test\par
\bf 测试 Test\par
\it 测试 Test\par
\bi 测试 Test\par
\ss 测试 Test\par
\tt 测试 Test\par
\tf 测试 $\sum_{i=0}^nx_i$
\stoptext
```

**Comment by liyanrui** [comment]
如果你没有像 notoserifcjksc 这样成套的字体，可以分别给 bf, it, bi 指定其他字体，例如

```
\definefallbackfamily
  [myfont]
  [rm]
  [simsun] % font family name
  [bf={name:simhei},
    it={name:kaiti},
    bi={name:youyuan},
    preset=range:chinese]
```

这种方式实际上相当于 \setupzhfonts[serif][regular=..., bold=..., italic= ..., bolditalic=...] 了。
