### ISSUE TITLE
怎麼自定義數學字體？

### ISSUE THREAD

**Issue by walkthetalk** [liyanrui/zhfonts#16]
如想使用notosansmath字體作爲數學公式默認字體，應如何設置？

**Comment by liyanrui** [comment]
我没有 notosansmath 这个字体。你试试

```
$ mtxrun --script font --list --all --pattern=notosansmath
```

如果命令输出结果中的 `familyname` 一栏里有 `notosansmath`，那么下面的例子应该能切换数学字体。

```
\usemodule[zhfonts]
\definefontfamily[zhfonts][mm][notosansmath]
\setupbodyfont[zhfonts,11pt]
\starttext
测试 $x^2 + y^2$
\stoptext
```

**Comment by liyanrui** [comment]
刚才我下了一个 notosansmath。

字体能被加载和使用，不过，ConTeXt 会报错：

```
Math error: parameter 'supshiftup' with id 51 in style 0 is not set
```

应该是这字体不够健全吧。你需要换个别的字体用了。

**Comment by liyanrui** [comment]
有一种偷梁换柱的办法可以暂时用 noto sans math

\usemodule[zhfonts]
\definefallbackfamily[zhfonts][mm][noto sans math][range={0x0000-0x1ffff},force=yes]
\definefontfamily[zhfonts][mm][xitsmath]
\switchtobodyfont[zhfonts,11pt]

\starttext
Test Noto Sasn Math Fonts
\startformula
\sqrt[3]{x}
\stopformula
\stoptext

**Comment by walkthetalk** [comment]
谢谢，ConTeXt不完全支持这个字体具体是什么意思？如果想让ConTeXt支持自定义的数学字体需要怎么做？

**Comment by liyanrui** [comment]
> 谢谢，ConTeXt不完全支持这个字体具体是什么意思？如果想让ConTeXt支持自定义的数学字体需要怎么做？

应该是字体自身的问题。我是从 「https://fonts.google.com/noto/specimen/Noto+Sans+Math」下载的字体，遇到上述问题后，我去邮件列表问了一下，Mikael Sundqvist 提醒，google 官网的 noto sans math 不是最新的。然后，从「https://github.com/notofonts/math/releases/tag/NotoSansMath-v2.539」下了字体包，解包后，子目录 full/ttf 目录里的 ttf 字体是最新的，用它就没问题了。

```TEX
\usemodule[zhfonts]
\starttypescript[math][notomath]
  \definefontsynonym[MathRoman][file:NotoSansMath-Regular.ttf][features=default]
\stoptypescript
\setupzhfonts[math][notomath]

\startTEXpage[offset=4pt]
测试 $a + \sqrt{b} + x^2$
\stopTEXpage
```

[foo.pdf](https://github.com/liyanrui/zhfonts/files/11167161/foo.pdf)

**Comment by walkthetalk** [comment]
貌似正文可以，在表头的还是不行
```
\starttypescript[math][notomath]
  \definefontsynonym[MathRoman][name:notosansmath][features=default]
\stoptypescript
\setupzhfonts[math][notomath]

\startTEXpage[offset=4pt]
\bTABLE
\bTABLEhead
\bTR
  \bTH $a + \sqrt{b} + x^2$ \eTH
\eTR
\eTABLEhead
\eTABLE

测试 $a + \sqrt{b} + x^2$
\stopTEXpage
```

**Comment by liyanrui** [comment]
> 貌似正文可以，在表头的还是不行

TABLE 的表头，默认用的是粗体。上面定义的数学字体，没有粗体，就出问题了。如果给数学字体设置一个粗体：

```TEX
\starttypescript[math][notomath]
\definefontsynonym[MathRoman][name:noto sans math][features=default]
\definefontsynonym[MathRomanBold][name:xits math bold][features=default]
\stoptypescript
```

这样就没问题了。

或者在表格里，用 `\tf` 将字体设为 Normal：

```TEX
\bTH \tf $a + \sqrt{b} + x^2$ \eTH
```

**Comment by walkthetalk** [comment]
明白了，十分感谢

**Comment by liyanrui** [comment]
> 明白了，十分感谢。 好像Unicode中为数学符号的粗、斜各种变种定义了专用码点， 这一款字体中是包含了所有码点的， 不知是否有手段改变ConTeXt的实现方式，用不同码点去描述变化，而不是通过更改字体进行处理？ https://notofonts.github.io/math/proof/glyphs.html https://symbl.cc/cn/unicode/blocks/mathematical-alphanumeric-symbols/

关于数学粗体，Hans 在 fonts-mkiv.pdf 的 7.3 节有一些讨论，不过我看不懂他在说啥。这个 PDF 你在 ConTeXt 里搜一下：

```console
$ mtxrun --script base --search fonts-mkiv.pdf 
``` 

另外，下面的代码应该能支持粗体，应该是伪粗体，我也不懂它是怎么实现的，我是从 texmf-context/tex/context/fonts/mkiv 目录里抄来的：

```TEX
\usemodule[zhfonts]
\definefontfeature[notosans-math-bold][boldened]
\starttypescript[math][notomath]
  \definefontsynonym[MathRoman][name:notosansmath][features={math\mathsizesuffix,mathextra}]
  \definefontsynonym[MathRomanBold][name:notosansmath][features={math\mathsizesuffix,notosans-math-bold,mathextra}]
\stoptypescript
\setupzhfonts[math][notomath]
```

**Comment by walkthetalk** [comment]
看了下unicode那一節，應該已經支持了，關於bold math一節，我的理解是：
bold math 是與普通math並列的一種環境，兩個不是包含的關係，所以要求有bold math對應的字體
換句話說，一個字符在普通math中有regular/bold的變形，在boldmath中照樣有regular/bold的變形，只是在bold math中bold變得更粗。

**Comment by liyanrui** [comment]
> 換句話說，一個字符在普通math中有regular/bold的變形，在boldmath中照樣有regular/bold的變形，只是在bold math中bold變得更粗。

这样看，那 `\definefontfeature[notosans-math-bold][boldened]` 应该就是前者吧。我在 font-mkiv.pdf 手册里查不到 `boldened` 这个词。字体方面，文档太少了。Hasn 写的那些，我总觉得过于晦涩。

**Comment by walkthetalk** [comment]
你貼的那段代碼在ConTeXt內部的處理方式不得而知，恐怕得作者解釋一下纔行。
Hans的母語應該也不是英文吧，若是如此，晦澀也就是可以理解了。
