### ISSUE TITLE
能否扩展一下zhfonts?

### ISSUE THREAD

**Issue by walkthetalk** [liyanrui/zhfonts#7]
能否扩展一下zhfonts，使得我们可以定义多套字体，就是说每一套字体都可以设置中、英文和sans、mono等字体
用的时候可以选择其中一套作为bodyfonts，其他的也可以任意切换使用

**Comment by liyanrui** [comment]
可以用 \setupzhfonts 宏自己写几个字体模块文件，用哪套字体，就 \usemodule[哪套字体]。
